# -*- coding: utf-8 -*-
"""CNN_All_Optimizers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsfLghn2vmb0yMoaGAFo72Mx5IaTvE7Y

**IMPORTING LIBRARIES**
"""

import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

"""**IMPORTING DATASET**"""

import os

# Define the path to the dataset directory
dataset_path = "/content/drive/MyDrive/Breast_cancer"

# Get the list of image files
image_files = []
labels = []

# Iterate over the directories
for class_name in ['benign', 'malignant', 'normal']:
    class_path = os.path.join(dataset_path, class_name)
    for filename in os.listdir(class_path):
        image_path = os.path.join(class_path, filename)
        image_files.append(image_path)
        labels.append(class_name)

# Convert labels to numerical values
from tensorflow.keras.utils import to_categorical

"""**CONVERTING LABELS INTO NUMERICAL VALUES**"""

# Convert labels to numerical values
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)
# Convert labels to one-hot encoded format
labels = to_categorical(labels)

"""**SHAPE AND SIZE OF THE DATASET**"""

print(labels.shape)
print(len(image_files))

"""**SPLITING THE DATASET**"""

from sklearn.model_selection import train_test_split
# Splitting the data into training and test sets (80% training, 20% test)
X_train, X_test, y_train, y_test = train_test_split(image_files, labels, test_size=0.2, random_state=42, stratify=labels)

"""**LENGHT OF THE TARIN AND TEST DATA**"""

print(len(X_train),len(y_train))
print(len(X_test),len(y_test))

"""**LOADING AND PREPROCESSING THE IMAGES**"""

# Define a function to load and preprocess the images
def load_preprocess_image(image_path):
    image = Image.open(image_path)
    image = image.resize((150, 150))
    image = image.convert('L')
    image = np.array(image)
    image = image.reshape((150, 150, 1))
    image = image.astype('float32') / 255.0
    return image

X_train = [str(image_path) for image_path in X_train]
X_test = [str(image_path) for image_path in X_test]

# Load and preprocess the training images and labels
X_train = [load_preprocess_image(image_path) for image_path in X_train]
X_train = np.array(X_train)
y_train= np.array(y_train)

# Load and preprocess the testing images and labels
X_test = [load_preprocess_image(image_path) for image_path in X_test]
X_test = np.array(X_test)
y_test = np.array(y_test)

print(X_train.shape, y_train.shape)
print(X_test.shape,y_test.shape)

"""**CREATING THE MODEL**"""

# Initialize the model
model = Sequential()

# Add convolutional layers
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

# Add more convolutional layers
model.add(Conv2D(256, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

# Flatten the output
model.add(Flatten())

# Add dense layers
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))

# model.add(Dense(1, activation='sigmoid'))
model.add(Dense(3, activation='softmax'))

"""

1. **Adam Optimizer**

"""

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

# Compile the model
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
# Train the model
history = model.fit(X_train, y_train, batch_size=32, epochs=30, validation_split=0.1)

"""* **TRAIN AND TEST ACCURACY PERCENTAGE**



* **TRAIN AND TEST LOSS PEECENTAGE**
"""

train_loss, train_accuracy = model.evaluate(X_train, y_train, verbose=0)
val_loss, val_accuracy = model.evaluate(X_test, y_test, verbose=0)

print(f'Training Accuracy: {train_accuracy*100:.2f}%')
print(f'Train Loss: {train_loss:.2f}%')
print(f'Test Accuracy: {val_accuracy*100:.2f}%')
print(f'Test Loss: {val_loss:.2f}%')

"""**CLASSIFICATION REPORT**



"""

import numpy as np
from sklearn.metrics import classification_report, accuracy_score

# Assuming you have X_test, y_test as your test data

# Make predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Classification report and accuracy
print('Classification Report:')
print(classification_report(y_true, y_pred_classes))

print(f'Accuracy: {accuracy_score(y_true, y_pred_classes)*100:.2f}')

"""**GRAPH FOR ACCURACY AND LOSS**"""

# Plotting accuracy and loss over epochs
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""
2.   **SGD Optimizer**

"""

#the learning rate is too high so the validation loss is increasing and the validation accuracy is decreasing which leads to over fitting
#optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
#so we need to decrease the learning rate 0.001
optimizer = tf.keras.optimizers.SGD(learning_rate=0.0001)
# Compile the model
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
# Train the model
history = model.fit(X_train, y_train, batch_size=32, epochs=10, validation_split=0.1)

"""* **TRAIN AND TEST ACCURACY PERCENTAGE**



* **TRAIN AND TEST LOSS PEECENTAGE**
"""

train_loss, train_accuracy = model.evaluate(X_train, y_train, verbose=0)
val_loss, val_accuracy = model.evaluate(X_test, y_test, verbose=0)

print(f'Training Accuracy: {train_accuracy*100:.2f}%')
print(f'Train Loss: {train_loss*100:.2f}%')
print(f'Test Accuracy: {val_accuracy*100:.2f}%')
print(f'Test Loss: {val_loss*100:.2f}%')

"""**CLASSIFICATION REPORT**"""

import numpy as np
from sklearn.metrics import classification_report, accuracy_score

# Assuming you have X_test, y_test as your test data

# Make predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Classification report and accuracy
print('Classification Report:')
print(classification_report(y_true, y_pred_classes))

print(f'Accuracy: {accuracy_score(y_true, y_pred_classes)*100:.2f}')

"""**GRAPH FOR ACCURACY AND LOSS**"""

# Plotting accuracy and loss over epochs
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""3. **RMSprop Optimizer**"""

optimizer = tf.keras.optimizers.RMSprop(learning_rate=0.001)
# Compile the model
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
# Train the model

history = model.fit(X_train, y_train, batch_size=32, epochs=10, validation_split=0.1)

"""* **TRAIN AND TEST ACCURACY PERCENTAGE**



* **TRAIN AND TEST LOSS PEECENTAGE**
"""

train_loss, train_accuracy = model.evaluate(X_train, y_train, verbose=0)
val_loss, val_accuracy = model.evaluate(X_test, y_test, verbose=0)

print(f'Training Accuracy: {train_accuracy*100:.2f}%')
print(f'Train Loss: {train_loss*100:.2f}%')
print(f'Test Accuracy: {val_accuracy*100:.2f}%')
print(f'Test Loss: {val_loss*100:.2f}%')

"""**CLASSIFICATION REPORT**"""

import numpy as np
from sklearn.metrics import classification_report, accuracy_score

# Assuming you have X_test, y_test as your test data

# Make predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Classification report and accuracy
print('Classification Report:')
print(classification_report(y_true, y_pred_classes))

print(f'Accuracy: {accuracy_score(y_true, y_pred_classes)*100:.2f}')

"""**GRAPH FOR ACCURACY AND LOSS**"""

# Plotting accuracy and loss over epochs
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""4. **Adagrad Optimizer**"""

optimizer = tf.keras.optimizers.Adagrad(learning_rate=0.01)
# Compile the model
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
# Train the model

history = model.fit(X_train, y_train, batch_size=32, epochs=10, validation_split=0.1)

"""* **TRAIN AND TEST ACCURACY PERCENTAGE**



* **TRAIN AND TEST LOSS PEECENTAGE**
"""

train_loss, train_accuracy = model.evaluate(X_train, y_train, verbose=0)
val_loss, val_accuracy = model.evaluate(X_test, y_test, verbose=0)

print(f'Training Accuracy: {train_accuracy*100:.2f}%')
print(f'Train Loss: {train_loss*100:.2f}%')
print(f'Test Accuracy: {val_accuracy*100:.2f}%')
print(f'Test Loss: {val_loss*100:.2f}%')

"""**CLASSIFICATION REPORT**"""

import numpy as np
from sklearn.metrics import classification_report, accuracy_score

# Assuming you have X_test, y_test as your test data

# Make predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Classification report and accuracy
print('Classification Report:')
print(classification_report(y_true, y_pred_classes))

print(f'Accuracy: {accuracy_score(y_true, y_pred_classes)*100:.2f}')

"""**GRAPH FOR ACCURACY AND LOSS**"""

# Plotting accuracy and loss over epochs
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""5. **Adadelta Optimizer**"""

optimizer = tf.keras.optimizers.Adadelta()
# Compile the model
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
# Train the model

history = model.fit(X_train, y_train, batch_size=32, epochs=10, validation_split=0.1)

"""* **TRAIN AND TEST ACCURACY PERCENTAGE**



* **TRAIN AND TEST LOSS PEECENTAGE**
"""

train_loss, train_accuracy = model.evaluate(X_train, y_train, verbose=0)
val_loss, val_accuracy = model.evaluate(X_test, y_test, verbose=0)

print(f'Training Accuracy: {train_accuracy*100:.2f}%')
print(f'Train Loss: {train_loss*100:.2f}%')
print(f'Test Accuracy: {val_accuracy*100:.2f}%')
print(f'Test Loss: {val_loss*100:.2f}%')

"""**CLASSIFICATION REPORT**"""

import numpy as np
from sklearn.metrics import classification_report, accuracy_score

# Assuming you have X_test, y_test as your test data

# Make predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Classification report and accuracy
print('Classification Report:')
print(classification_report(y_true, y_pred_classes))

print(f'Accuracy: {accuracy_score(y_true, y_pred_classes)*100:.2f}')

"""**GRAPH FOR ACCURACY AND LOSS**"""

# Plotting accuracy and loss over epochs
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""**TESTING THE MODEL**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Given data
x = ['Adam', 'SGD', 'RMSprop', 'Adagrad', 'Adadelta']
y = [96.99, 98.18, 98.26, 98.26, 98.26]

# Create a Seaborn bar plot
sns.set(style="whitegrid")
plt.figure(figsize=(10, 6))
sns.barplot(x=x, y=y, palette="viridis")

# Adding labels and title
plt.xlabel("Optimizers")
plt.ylabel("Training Accuracy")
plt.title("Training Accuracy of Different Optimizers")

# Display the plot
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Given data
x = ['Adam', 'SGD', 'RMSprop', 'Adagrad', 'Adadelta']
y = [82.91, 81.96, 83.23, 83.23, 83.23]

# Create a Seaborn bar plot
sns.set(style="whitegrid")
plt.figure(figsize=(10, 6))
sns.barplot(x=x, y=y, palette="coolwarm")

# Adding labels and title
plt.xlabel("Optimizers")
plt.ylabel("Validation Accuracy")
plt.title("Validation Accuracy of Different Optimizers")

# Display the plot
plt.show()

# Define a function to load and preprocess a single image
def load_preprocess_single_image(image_path):
    image = Image.open(image_path)
    image = image.resize((150, 150))
    image = image.convert('L')
    image = np.array(image)
    image = image.reshape((1, 150, 150, 1))
    image = image.astype('float32') / 255.0
    return image

# Path to the image in your Google Drive
image_path = "/content/drive/MyDrive/Breast_cancer/malignant/malignant (10).png"  # Replace with your image path

# Load and preprocess the single image
test_image = load_preprocess_single_image(image_path)

# Make predictions
predictions = model.predict(test_image)
predicted_class = np.argmax(predictions)

# Decode the predicted class
classes = ['benign', 'malignant', 'normal']
predicted_label = classes[predicted_class]

print(f"Predicted class: {predicted_label}")

if (predicted_label == 'normal'):
  print("You're in Normal condition no need to worry.")
elif (predicted_label == 'benign'):
  print("Benign the cells are not yet cancerous, but they have the potential to become malignant consult the doctor.")
elif (predicted_label == 'malignant'):
  print("Malignant the tumors are cancerous. The cells can grow and spread to other parts of the body.")
else:
  print("The Image which is under consideration is unpredictable by the model we will try again")

# Path to the image in your Google Drive
image_path = "/content/drive/MyDrive/b.webp"  # Replace with your image path

# Load and preprocess the single image
test_image = load_preprocess_single_image(image_path)

# Make predictions
predictions = model.predict(test_image)
predicted_class = np.argmax(predictions)

# Decode the predicted class
classes = ['benign', 'malignant', 'normal']
predicted_label = classes[predicted_class]

print(f"Predicted class: {predicted_label}")

if (predicted_label == 'normal'):
  print("You're in Normal condition no need to worry.")
elif (predicted_label == 'benign'):
  print("Benign the cells are not yet cancerous, but they have the potential to become malignant consult the doctor.")
elif (predicted_label == 'malignant'):
  print("Malignant the tumors are cancerous. The cells can grow and spread to other parts of the body.")
else:
  print("The Image which is under consideration is unpredictable by the model we will try again")

# Path to the image in your Google Drive
image_path = "/content/drive/MyDrive/Breast_cancer/normal/normal (1).png"  # Replace with your image path

# Load and preprocess the single image
test_image = load_preprocess_single_image(image_path)

# Make predictions
predictions = model.predict(test_image)
predicted_class = np.argmax(predictions)

# Decode the predicted class
classes = ['benign', 'malignant', 'normal']
predicted_label = classes[predicted_class]

print(f"Predicted class: {predicted_label}")

if (predicted_label == 'normal'):
  print("You're in Normal condition no need to worry.")
elif (predicted_label == 'benign'):
  print("Benign the cells are not yet cancerous, but they have the potential to become malignant consult the doctor.")
elif (predicted_label == 'malignant'):
  print("Malignant the tumors are cancerous. The cells can grow and spread to other parts of the body.")
else:
  print("The Image which is under consideration is unpredictable by the model we will try again")

"""**CODE FINISHED**"""